#Abrir o navegador, acessar o site do jogo da cobrinha, dar play, e criar um codigo que zere o jogo
import pyautogui
from time import sleep
pyautogui.click(861, 744)
sleep(0.2)
pyautogui.hotkey('ctrl', 't')
sleep(1)
pyautogui.write('file:///C:/Users/deric/OneDrive/Documentos/snake_game.html')
sleep(1)
pyautogui.press('enter')
sleep(1)
pyautogui.click(685, 426)
sleep(1)
pyautogui.press('right')
sleep(0.75)
pyautogui.press('down')
sleep(1.65)
pyautogui.press('left')
sleep(1.53)
pyautogui.press('up')
sleep(0.1)
pyautogui.press('right')
sleep(1.53)
pyautogui.press('up')
sleep(0.1)
pyautogui.press('left')
sleep(1.67)
pyautogui.press('up')
sleep(0.1)
pyautogui.press('right')
sleep(1.6)
pyautogui.press('up')
sleep(0.1)
pyautogui.press('left')
sleep(1.67)
pyautogui.press('up')
sleep(0.1)
pyautogui.press('right')
sleep(1.6)
pyautogui.press('up')
sleep(0.1)
pyautogui.press('left')
sleep(1.67)
pyautogui.press('up')
sleep(0.1)
pyautogui.press('right')
sleep(1.6)
pyautogui.press('up')
sleep(0.1)
pyautogui.press('left')
sleep(1.67)
pyautogui.press('up')
sleep(0.1)
